### ISSUE TITLE
Add support for Factions and Towny

### ISSUE THREAD

**Issue by Katelyn-SN** [SBPrime/BlocksHub#12]
Implementing this should not be that hard

Both are access controllers

Factions: http://dev.bukkit.org/bukkit-plugins/factions/

Towny: http://palmergames.com/towny/

**Comment by SBPrime** [comment]
1. Please provide a link to the plugins you mentioned.
2. Those plugins are loggers or access controllers?

**Comment by tf101-wizard** [comment]
Post updated with requested information sorry for the delay.

**Comment by SBPrime** [comment]
@Katelyn-SN Sorry it took so long but I managed to find time to work on adding support for the plugins.  Factions support is done, Unfortunately I have some trouble with the towny plugin. When there is no town everything works ok. Maybe you can help me. 
* Using Player A i set up a town
 * /town new test
 * /town claim 5
* Then I login using Player B

Unfortunately player B cant move and the screen keeps moving in random directions. Player A can move, place blocks normally. Can you provide me some info what I did wrong? All I need is a town where player A can build and player B can't build.

**Comment by Katelyn-SN** [comment]
Well that is what happens when Towny crashes into save mode server logs should tell you whats going on i would think.

**Comment by SBPrime** [comment]
Hmm... I did not notice anything on the console, I'll look at it later when I'm back home. To be 100% sure that you understood me correctly Player A can build and walk around when Player B is online. I assume that I did all the steps correctly while crating the town?

**Comment by TheDoctorsLife** [comment]
cool
