### ISSUE TITLE
Also have issues with prism v2.0.6

### ISSUE THREAD

**Issue by GoadingGoat** [SBPrime/BlocksHub#25]
Have Prism v2.0.6 and BlocksHub2.01 and getting large amounts of console errors, one error per block changed with worldedit/fawe.
![blockshub errors](https://cloud.githubusercontent.com/assets/11308755/18089689/4afceb24-6f15-11e6-84de-74ab619ca788.PNG)

**Comment by SBPrime** [comment]
Apparently there are 2 plugins that have the same name. Please send me the link to the exact version that you have used.

**Comment by GoadingGoat** [comment]
https://dev.bukkit.org/bukkit-plugins/prism/files/66-prism-v2-0-6/

**Comment by SBPrime** [comment]
Duplicate of #22
