### ISSUE TITLE
Please add the ability to manually disable hooks from the config

### ISSUE THREAD

**Issue by zombachu** [SBPrime/BlocksHub#26]
I'm currently using a custom fork of Prism, which has conflicts with this plugin. In previous versions this wasn't an issue as I could've just not uploaded the Prism bridge, but now that everything is in 1 jar and it autodetects that I'm using Prism, it's causing a bunch of errors. I know my own case is a little out of the ordinary because I use both Prism and CoreProtect (and have BlocksHub installed for CoreProtect), but I think my suggestion would be a useful addition in general.

**Comment by SBPrime** [comment]
I'll see what I can do :D For now I would suggest:
1. Download the BlocksHub.jar
2. Open it with some zip util (7zip, rar, etc).
3. Navigate to plugins/bukkit/loggers
4. Remove the BlockshHub-Prism.jar
5. Save the modified jar file and upload to server

**Comment by zombachu** [comment]
Thanks!
