### ISSUE TITLE
Whitelist all worlds

### ISSUE THREAD

**Issue by AaronMcHale** [SBPrime/BlocksHub#37]
Is it possible to whitelist every world?

I tried using `*` or `'*'` as the world name which doesn't work, also tried proper regex `[\s\S]*` which also doesn't match.

**Comment by SBPrime** [comment]
Did you try ```.*```?

**Comment by AaronMcHale** [comment]
That worked, thanks.

I couldn't seem to find the `.*` documented, the only thing I saw was `world.*`, which wasn't obvious that it could be modified to just `.*`.  Might be a good idea to document that better?

Thanks
-Aaron

**Comment by SBPrime** [comment]
In the documentation it says that its a regexp.

**Comment by AaronMcHale** [comment]
Yes that's true, although it seems the first regex I tried `[\s\S]*` didn't seem to work, even those it does validate as correct.

That could more just be one of the oddities of the Java Regex Matchers, but then it might be worth explicitly documenting `.*` as an example since I imagine it's quite a common use case.
