### ISSUE TITLE
Illegal reflective access operation

### ISSUE THREAD

**Issue by klugemonkey** [SBPrime/BlocksHub#39]
I get this.  Really don't know what it means either.

[06:22:18 INFO]: [BlocksHub] Enabling BlocksHub v3.0.0
>WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.primesoft.blockshub.utils.Reflection (file:/var/games/minecraft/servers/survival/plugins/BlocksHub-3.0.0.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.primesoft.blockshub.utils.Reflection
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by SBPrime** [comment]
I assume that you upgraded, java. BlocksHub relays on reflection to work properly. Please consult java 9 documentation on how to disable the warning.
