### ISSUE TITLE
Re-Add Support for Logblock, Worldguard and Griefprevention

### ISSUE THREAD

**Issue by Phreag** [SBPrime/BlocksHub#40]
Really missing these functions in 3.0.0, could you please re-add them?

**Comment by SBPrime** [comment]
Unfortunately WorldGuard will not be added because currently it depends on WorldEdit and I do not want to add WE dependency in BlocksHub. 

LogBlock: will be added,
Griefprevention: will be added,

**Comment by SBPrime** [comment]
Done in 3.1.0
